<?php

declare(strict_types=1);

namespace Eleph\Codegen\Tests\Command;

use Eleph\Codegen\GeneratedFile;
use Eleph\Codegen\Protocol\CompilerRequest;
use Eleph\Codegen\Protocol\Envelope;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\TestCase;
use RuntimeException;

/**
 * The whole program, driven the way Elephentity drives it.
 *
 * This runs the real binary as a subprocess with a request on stdin, because that is
 * the interface — a class test would prove the pieces work and say nothing about the
 * entrypoint that is actually the contract. It is also what makes these tests portable
 * to a rewrite: the assertions are about bytes on disk and an exit code, and a
 * reimplementation in another language has to satisfy them unchanged.
 */
#[CoversNothing]
final class GenerateCommandTest extends TestCase
{
    private string $project;

    protected function setUp(): void
    {
        $this->project = sys_get_temp_dir() . '/eleph-codegen-' . bin2hex(random_bytes(6));

        mkdir($this->project . '/tools/builders', 0o775, true);
        $this->writeBuilder();
        $this->writeConfig();
    }

    protected function tearDown(): void
    {
        $this->remove($this->project);
    }

    public function testABuildersFilesAreWrittenUnderASignedHeader(): void
    {
        $result = $this->generate();

        self::assertSame(0, $result['exit'], $result['stderr']);

        // The exact bytes, header included. The digest covers the path and the body, so
        // this pins the signing format itself — anything that reproduces this program
        // has to produce this file byte for byte or every existing tree fails to verify.
        self::assertSame(
            <<<'PHP'
                <?php

                declare(strict_types=1);

                /*
                 * GENERATED BY Elephentity — DO NOT EDIT.
                 *
                 * Regenerate with `eleph generate`. This file is machine-owned: edits are
                 * detected by the build and rejected.
                 *
                 * path:   Post.php
                 * digest: sha256:cff42c4dd731d4940868532b99381523560408f85b8d8d103321e24bc02cde0f
                 */

                namespace Fixture;

                final class Post
                {
                }

                PHP,
            (string) file_get_contents($this->project . '/generated/Post.php'),
        );
    }

    public function testWhatTheCompilerContributedIsWrittenAndSignedToo(): void
    {
        // The manifests Elephentity compiles itself arrive addressed to a target and are
        // written with it. Nothing on disk says which side of the pipe a file came from.
        $this->generate(contributions: ['php' => [new GeneratedFile('manifest.php', "return [];\n")]]);

        $manifest = (string) file_get_contents($this->project . '/generated/manifest.php');

        self::assertStringContainsString('GENERATED BY Elephentity', $manifest);
        self::assertStringContainsString('path:   manifest.php', $manifest);
        self::assertStringEndsWith("return [];\n", $manifest);
    }

    public function testASecondRunChangesNothing(): void
    {
        $this->generate();

        // The gate the whole locked-file design rests on: if regenerating is not stable,
        // every CI run reports a diff and the check stops meaning anything.
        $result = $this->generate(['--check']);

        self::assertSame(0, $result['exit'], $result['stdout'] . $result['stderr']);
        self::assertStringContainsString('up to date', $result['stdout']);
    }

    public function testAHandEditedFileFailsTheCheck(): void
    {
        $this->generate();

        $post = $this->project . '/generated/Post.php';
        file_put_contents($post, str_replace('final class Post', 'final class Posts', (string) file_get_contents($post)));

        $result = $this->generate(['--check']);

        self::assertSame(1, $result['exit']);
        self::assertStringContainsString('Hand-edited', $result['stdout']);
    }

    public function testAFileTheSpecNoLongerProducesIsSweptButOnlyItsOwnKind(): void
    {
        $this->generate();

        file_put_contents($this->project . '/generated/Stale.php', "<?php\n");
        file_put_contents($this->project . '/generated/notes.md', "mine\n");

        $this->generate();

        self::assertFileDoesNotExist($this->project . '/generated/Stale.php');

        // Deleting is the one thing worth being timid about: a mistyped output directory
        // should not take somebody's notes with it.
        self::assertFileExists($this->project . '/generated/notes.md');
    }

    public function testCheckWritesNothingAtAll(): void
    {
        $result = $this->generate(['--check']);

        self::assertSame(1, $result['exit']);
        self::assertFileDoesNotExist($this->project . '/generated/Post.php');
    }

    public function testAMissingBuilderFailsTheBuildAndSaysWhereItLooked(): void
    {
        $this->writeConfig(builder: 'eleph-gen-nowhere');

        $result = $this->generate();

        self::assertSame(1, $result['exit']);
        self::assertStringContainsString('No builder "eleph-gen-nowhere"', $result['stdout']);
        self::assertStringContainsString('does not fetch builders', $result['stdout']);
        self::assertFileDoesNotExist($this->project . '/generated/Post.php');
    }

    public function testAnUnknownTargetIsRefusedRatherThanIgnored(): void
    {
        $result = $this->generate(['--targets', 'rust']);

        self::assertSame(2, $result['exit']);
        self::assertStringContainsString('Unknown target(s): rust', $result['stdout']);
    }

    public function testNothingOnStdinIsSaidPlainly(): void
    {
        $result = $this->invoke([], input: '');

        self::assertSame(2, $result['exit']);
        self::assertStringContainsString('Expected a compiled spec on stdin', $result['stdout']);
    }

    public function testARequestFromAnotherIrVersionIsRefusedBeforeAnythingRuns(): void
    {
        $result = $this->invoke([], input: (string) json_encode([
            'elephentity' => Envelope::VERSION,
            'irVersion' => '99.0',
            'schema' => [],
        ]));

        self::assertSame(2, $result['exit']);
        self::assertStringContainsString('IR version mismatch', $result['stdout']);
        self::assertFileDoesNotExist($this->project . '/generated/Post.php');
    }

    /**
     * @param list<string>                       $arguments
     * @param array<string, list<GeneratedFile>> $contributions
     *
     * @return array{exit: int, stdout: string, stderr: string}
     */
    private function generate(array $arguments = [], array $contributions = []): array
    {
        return $this->invoke($arguments, (string) json_encode(CompilerRequest::encode(
            ['entities' => ['Post' => ['name' => 'Post']]],
            $contributions,
        )));
    }

    /**
     * @param list<string> $arguments
     *
     * @return array{exit: int, stdout: string, stderr: string}
     */
    private function invoke(array $arguments, string $input): array
    {
        $command = [
            PHP_BINARY,
            dirname(__DIR__, 2) . '/bin/eleph-codegen',
            'generate',
            '--project',
            $this->project,
            ...$arguments,
        ];

        $stdin = tempnam(sys_get_temp_dir(), 'eleph-in-');

        if (false === $stdin) {
            throw new RuntimeException('Could not stage stdin.');
        }

        file_put_contents($stdin, $input);

        $descriptors = [0 => ['file', $stdin, 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']];
        $pipes = [];
        $process = proc_open($command, $descriptors, $pipes);

        if (!is_resource($process)) {
            throw new RuntimeException('Could not run eleph-codegen.');
        }

        $stdout = (string) stream_get_contents($pipes[1]);
        $stderr = (string) stream_get_contents($pipes[2]);

        fclose($pipes[1]);
        fclose($pipes[2]);

        $exit = proc_close($process);
        unlink($stdin);

        return ['exit' => $exit, 'stdout' => $stdout, 'stderr' => $stderr];
    }

    /**
     * A builder that generates one class per entity, in as few lines as the contract
     * allows: read stdin, write stdout, exit 0.
     */
    private function writeBuilder(): void
    {
        $path = $this->project . '/tools/builders/eleph-gen-fixture';

        file_put_contents($path, sprintf(<<<'PHP'
            #!/usr/bin/env php
            <?php

            $request = json_decode(file_get_contents('php://stdin'), true);

            if ($request['elephentity'] !== %d || $request['irVersion'] !== %s) {
                fwrite(STDERR, "eleph-gen-fixture: wrong protocol\n");
                exit(1);
            }

            $files = [];

            foreach (array_keys($request['schema']['entities'] ?? []) as $entity) {
                $files[] = [
                    'path' => $entity . '.php',
                    'body' => "namespace Fixture;\n\nfinal class " . $entity . "\n{\n}\n",
                ];
            }

            echo json_encode([
                'elephentity' => %1$d,
                'irVersion' => %2$s,
                'headerStyle' => 'php',
                'extensions' => ['php'],
                'files' => $files,
                'errors' => [],
            ]);

            PHP, Envelope::VERSION, var_export(Envelope::IR_VERSION, true)));

        chmod($path, 0o775);
    }

    private function writeConfig(string $builder = 'eleph-gen-fixture'): void
    {
        file_put_contents($this->project . '/eleph.json', (string) json_encode([
            'spec' => 'spec',
            'targets' => ['php' => ['output' => 'generated', 'builder' => $builder]],
        ], JSON_PRETTY_PRINT));
    }

    private function remove(string $directory): void
    {
        if (!is_dir($directory)) {
            return;
        }

        foreach (scandir($directory) ?: [] as $entry) {
            if ('.' === $entry || '..' === $entry) {
                continue;
            }

            $path = $directory . '/' . $entry;

            is_dir($path) ? $this->remove($path) : unlink($path);
        }

        rmdir($directory);
    }
}
