<?php

declare(strict_types=1);

namespace Eleph\Codegen\Signing;

/**
 * How a generated file announces that it is generated, per output language.
 *
 * The digest covers everything after the header and the header is excluded by
 * *position*, so a verifier has to know how many lines to skip without having parsed
 * them. That is why `lines()` is declared rather than derived: the count is part of
 * what is being verified. `SignerTest` asserts that every case renders exactly the
 * number of lines it claims, because an off-by-one here silently shifts what the
 * digest covers.
 *
 * Changing a rendered header invalidates every signature written in that style, which
 * is intended — the header format is part of what is signed.
 */
enum HeaderStyle: string
{
    /** PHP's open tag and strict_types, then a block comment. */
    case Php = 'php';

    /** Line comments only: C-family languages, TypeScript included. */
    case LineComment = 'line-comment';

    public function lines(): int
    {
        return match ($this) {
            self::Php => 14,
            self::LineComment => 8,
        };
    }

    public function render(string $relativePath, string $digest): string
    {
        return match ($this) {
            // Byte-for-byte what the generator has always emitted. The trailing newline
            // puts a blank line between the header and the body, and brings the header
            // to exactly lines() lines.
            self::Php => <<<PHP
                <?php

                declare(strict_types=1);

                /*
                 * GENERATED BY Elephentity — DO NOT EDIT.
                 *
                 * Regenerate with `eleph generate`. This file is machine-owned: edits are
                 * detected by the build and rejected.
                 *
                 * path:   {$relativePath}
                 * digest: {$digest}
                 */

                PHP . "\n",
            self::LineComment => <<<TXT
                // GENERATED BY Elephentity — DO NOT EDIT.
                //
                // Regenerate with `eleph generate`. This file is machine-owned: edits are
                // detected by the build and rejected.
                //
                // path:   {$relativePath}
                // digest: {$digest}

                TXT . "\n",
        };
    }

    /**
     * Matches the digest line this style writes, capturing the digest.
     */
    public function digestPattern(): string
    {
        return match ($this) {
            self::Php => '/^ \* digest: (\S+)$/m',
            self::LineComment => '/^\/\/ digest: (\S+)$/m',
        };
    }
}
